Add caller code for scamper binary
m-lab/traceroute-caller pull request #3
Opened 2019-03-07 19:56 UTC by yachang

2019-03-07 21:36 UTC, pboothe requested changes
Lots of comments, but basically, I counted 4 subpackages that should be made: `connection`, `connectionwatcher`, `scamper`, and `ipcache`.  One you make those, and eliminate the `util` package, I think the code will be a lot cleaner, and `main` will be a lot smaller.

Please only have `main()` and flags in `package main`, and please don't create packages named `util`.  That way, the code in `main` that is hard to test can be checked by inspection to be correct, and we can test each subpackage independently.

Also, I worry about bugs in my design of the `uuid` spec, so would prefer that you use the library until the design has been validated in practice. That way, in case I was disastrously wrong in some way, I only have to fix one implementation.

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-:-L_P0ItHAJyT7yvxuTeo:bvzlc7r)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[caller.go, line 18 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_P1L-kCGwPLovBDYi1:-L_P1L-kCGwPLovBDYi2:b2zfeps) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/caller.go#L18)):*
> ```Go
> )
> 
> var SCAMPER_BIN = "/usr/local/bin/scamper"
> ```

Should be a flag
___
*[caller.go, line 19 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_P1NpH1D81C8RiAxLo:-L_P1NpH1D81C8RiAxLp:bx23tvz) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/caller.go#L19)):*
> ```Go
> 
> var SCAMPER_BIN = "/usr/local/bin/scamper"
> var OUTPUT_PATH = "/var/spool/scamper"
> ```

Also a flag.
___
*[caller.go, line 21 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_OyOlp5TsB5D5Pa6rH:-L_OyOlp5TsB5D5Pa6rI:b-ex6yjw) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/caller.go#L21)):*
> ```Go
> var OUTPUT_PATH = "/var/spool/scamper"
> 
> type Connection struct {
> ```

Should be in its own package `connection`
___
*[caller.go, line 31 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_Oytj67jc4RJAdtP4d:-L_Oytj67jc4RJAdtP4e:b-z9ck5p) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/caller.go#L31)):*
> ```Go
> // One line of ss output has format like:
> // Netid  State      Recv-Q Send-Q                  Local Address:Port                                   Peer Address:Port
> func ParseSSLine(line string) (*Connection, error) {
> ```

This should be in the package `connectionwatcher` and should be renamed to `parseSSLine` so that it is private to that package.
___
*[caller.go, line 58 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_Oz6gM5bs8REQDVQYg:-L_Oz6gM5bs8REQDVQYh:b-b9ijsb) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/caller.go#L58)):*
> ```Go
> }
> 
> func RunScamper(conn Connection) {
> ```

Please put in package `scamper` and rename to `Run`
___
*[caller.go, line 59 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_OxvCI4ce26_hVOUsZ:-L_OxvCI4ce26_hVOUs_:b-oytri) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/caller.go#L59)):*
> ```Go
> 
> func RunScamper(conn Connection) {
> 	command := exec.Command(SCAMPER_BIN, "-O", "json", "-I", "tracelb -P icmp-echo -q 3 -O ptr "+conn.remote_ip)
> ```

Please put `// TODO: convert to using sc_attach`
___
*[caller.go, line 106 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_OxCI3CElc-64rgtm_:-L_OxCI3CElc-64rgtma:btmzr12) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/caller.go#L106)):*
> ```Go
> }
> 
> //////////////////////////////////////////////////////////////
> ```

This should be in its own package `connectionwatcher` .
___
*[caller.go, line 151 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_OzQy0EdsKN7OOaObM:-L_OzQy0EdsKN7OOaObN:bg47v2b) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/caller.go#L151)):*
> ```Go
> }
> 
> func (c *ConnectionWatcher) Init() {
> ```

This function is never called?
___
*[caller.go, line 156 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_OxEx4DynudiQyh8LH:-L_OxEx4DynudiQyh8LI:b-zaxc22) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/caller.go#L156)):*
> ```Go
> }
> 
> var connWatcher ConnectionWatcher
> ```

This should be a local var of `main`
___
*[caller.go, line 162 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_Oyhbx9ffd6DzL8D-2:-L_Oyhbx9ffd6DzL8D-3:b-kcxft8) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/caller.go#L162)):*
> ```Go
> func main() {
> 	if len(os.Args) > 1 {
> 		OUTPUT_PATH = os.Args[1]
> ```

Please use the `flag` package. It is nice and easy to use.
___
*[caller.go, line 165 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_OyYHR-rMRRw1NoY_x:-L_OyYHR-rMRRw1NoY_y:bs42hvm) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/caller.go#L165)):*
> ```Go
> 	}
> 	connWatcher.GetConnections()
> 	for true {
> ```

`for {` is the same as `for true {` and the first is more idiomatic.
___
*[util/util.go, line 1 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_Ovwg_4e4cnUUaajk1:-L_Ovwg_4e4cnUUaajk2:bg7qixv) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/util/util.go#L1)):*
> ```Go
> package util
> ```

`util` is a bad name.  Everything here should be put into one or another different package.
___
*[util/util.go, line 21 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_P-t4VB-tmm4jpL6Ww:-L_P-t4VB-tmm4jpL6Wx:b-4xklwf) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/util/util.go#L21)):*
> ```Go
> // MakeFilename as logtime_clientIP.json, such as:
> // 2019-02-04T18:01:10Z-76.14.89.46.json
> func MakeFilename(ip string) string {
> ```

`Filename` should be a method attached to the `Connection` struct.
___
*[util/util.go, line 27 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_P03Yn-oq4vnFdhaCD:-L_P03Yn-oq4vnFdhaCE:b-m9iphc) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/util/util.go#L27)):*
> ```Go
> }
> 
> func GetHostname() string {
> ```

I think this can be deleted once you add some more command-line flags?
___
*[util/util.go, line 33 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_P4Dd_CmYS5W_JA1Qt:-L_P4Dda6zJgQScYn5-t:b-7hz4z0) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/util/util.go#L33)):*
> ```Go
> }
> 
> func MakeUUID(cookie string) (string, error) {
> ```

Please make `.UUID()` a method of `Connection` structs
___
*[util/util.go, line 41 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_Ow1D87RnCxwV5v5qt:-L_Ow1D87RnCxwV5v5qu:bvyfxke) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/util/util.go#L41)):*
> ```Go
> 	// cookie is a hexdecimal string
> 	result, _ := strconv.ParseUint(cookie, 16, 64)
> 	return fmt.Sprintf("%s_%d_%016X", GetHostname(), stat.ModTime().Unix(), uint64(result)), nil
> ```

Change to `return uuid.FromCookie(result)` then you can delete lots of other code.

Alternatively, you can add `FromSSCookie` as a function in the `uuid` library.  Either option is better than replicating its logic here.
___
*[util/util.go, line 70 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_P-Mip41X9HKthYt3i:-L_P-Mip41X9HKthYt3j:b3o4ct2) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141 [...]

2019-03-13 17:28 UTC, pboothe requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

___
*[caller.go, line 19 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_P1NpH1D81C8RiAxLo:-L_rwmZ19JvQz-l5QAG7:b10nhk) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/caller.go#L19)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Also a flag.
</blockquote></details>

Thanks for converting to a flag!  All caps is only for constants. This should be `outputPath`.  Same for all other variables which are flags. 
___
*[caller.go, line 21 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_OyOlp5TsB5D5Pa6rH:-L_s4rh--SpdGp9ih97T:b-ucfknh) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/caller.go#L21)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Should be in its own package `connection`
</blockquote></details>

Thanks!
___
*[caller.go, line 31 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_Oytj67jc4RJAdtP4d:-L_s4tPbD4CNaxy4HnXu:b-ucfknh) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/caller.go#L31)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

This should be in the package `connectionwatcher` and should be renamed to `parseSSLine` so that it is private to that package.
</blockquote></details>

Thanks!
___
*[caller.go, line 58 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_Oz6gM5bs8REQDVQYg:-L_s4v0LCwN5wED7HS8S:b-ucfknh) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/caller.go#L58)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Please put in package `scamper` and rename to `Run`
</blockquote></details>

Thanks!
___
*[caller.go, line 59 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_OxvCI4ce26_hVOUsZ:-L_s4mE61OZX5QNg51Nx:b-tl00pg) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/caller.go#L59)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Please put `// TODO: convert to using sc_attach`
</blockquote></details>

followed up in a separate comment.
___
*[caller.go, line 151 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_OzQy0EdsKN7OOaObM:-L_s4y4V5AahqLxNUJVq:b-ucfknh) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/caller.go#L151)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

This function is never called?
</blockquote></details>

Thanks!
___
*[caller.go, line 156 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_OxEx4DynudiQyh8LH:-L_s5-W62KFhh1kBaGNb:b6nj9ke) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/caller.go#L156)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

This should be a local var of `main`
</blockquote></details>

This should still be a local var of `main`
___
*[caller.go, line 162 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_Oyhbx9ffd6DzL8D-2:-L_s52fu81NZznzeIn2Z:b4bimjj) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/caller.go#L162)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Please use the `flag` package. It is nice and easy to use.
</blockquote></details>

Please call `flag.Parse()`
___
*[caller.go, line 165 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_OyYHR-rMRRw1NoY_x:-L_s5CYKBEJ4B2sToujY:b-8d3s65) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/caller.go#L165)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

`for {` is the same as `for true {` and the first is more idiomatic.
</blockquote></details>

Still true.
___
*[connection/connection.go, line 25 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_rxJne7zPizd84iwP6:-L_rxJne7zPizd84iwP7:b-xf0lnc) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/connection/connection.go#L25)):*
> ```Go
> 
> // MakeUUID returns uuid from cookie parsed from "ss -e" output.
> func MakeUUID(cookie string) (string, error) {
> ```

Should be a method attached to the `Connection` struct.

```go
func (c *Connection) UUID() (string, error) {
  ...
}
```
___
*[connection/connection.go, line 65 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_rxyW23PX26oRkDekb:-L_rxyW23PX26oRkDekc:b-c5eyy9) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/connection/connection.go#L65)):*
> ```Go
> 
> // ParseSSLine take one line output from "ss -e" and return the parsed connection.
> func ParseSSLine(line string) (*Connection, error) {
> ```

Should be in `connectionwatcher`, along with `ParseCookie` and `ParseIPAndPort`.  Then they can be renamed to `parseSSLine`, `parseCookie`, and `parseIPAndPort`.  Then it's clear that these functions are only used inside `connectionwatcher` and users of the library don't need to know about them. 
___
*[connectionwatcher/connectionwatcher.go, line 20 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_s1Gzp5QEnipEWKnSH:-L_s1Gzp5QEnipEWKnSI:b-oec0ei) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/connectionwatcher/connectionwatcher.go#L20)):*
> ```Go
> }
> 
> func (c *ConnectionWatcher) GetConnections() {
> ```

Should be `getConnections`
___
*[connectionwatcher/connectionwatcher.go, line 41 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_s0i8bAus-vnFfhAhk:-L_s0i8bAus-vnFfhAhl:b-wsgrdl) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/connectionwatcher/connectionwatcher.go#L41)):*
> ```Go
> }
> 
> func (c *ConnectionWatcher) GetPoolSize() int {
> ```

This function is only used in the test. No need to export it, just put the test in `package connectionwatcher` and then this can be renamed to `getPoolSize`
___
*[connectionwatcher/connectionwatcher.go, line 45 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_s0dCM5hn6abkd7Kyn:-L_s0dCN1OAjXiOrrh1v:brrhlz0) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/connectionwatcher/connectionwatcher.go#L45)):*
> ```Go
> }
> 
> func (c *ConnectionWatcher) GetCacheSize() int {
> ```

This function is never used. Delete it.
___
*[connectionwatcher/connectionwatcher.go, line 66 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_ryZZK-ce7V1q3Sd6h:-L_ryZZK-ce7V1q3Sd6i:b-4o8qiq) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/connectionwatcher/connectionwatcher.go#L66)):*
> ```Go
> }
> 
> func (c *ConnectionWatcher) Init() {
> ```

The regular go idiom is to have a function `New` in a package instead of `Init` on an existing struct.

```go
func New() *ConnectionWatcher {
  c := &ConnectionWatcher{
    recentIPCache: ipcache.New(),
    connectionPool: make(map[connection.Connection]bool),
  }
  c.getConnections()  // prepare the cache
  return c
}
```

It also allows all client of this library to save a line and do:
`connWatcher := connectionwatcher.New()`
___
*[ipcache/ipcache.go, line 10 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_rzT8t617MvvT57Z2b:-L_rzT8t617MvvT57Z2c:bcmboh9) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad [...]

2019-03-13 17:32 UTC, pboothe requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

___
*[util/util.go, line 1 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_Ovwg_4e4cnUUaajk1:-L_s5cmZ8YLYMYJ8q8Is:b-ucfknh) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/util/util.go#L1)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

`util` is a bad name.  Everything here should be put into one or another different package.
</blockquote></details>

Thanks!
___
*[util/util.go, line 33 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_P4Dd_CmYS5W_JA1Qt:-L_s65x_1xnXnjdNGQqk:bf4oy6l) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/util/util.go#L33)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Please make `.UUID()` a method of `Connection` structs
</blockquote></details>

Followed up in another comment.
___
*[util/util.go, line 41 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_Ow1D87RnCxwV5v5qt:-L_s5d_L6MAS1SB3U8If:b-ucfknh) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/util/util.go#L41)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Change to `return uuid.FromCookie(result)` then you can delete lots of other code.

Alternatively, you can add `FromSSCookie` as a function in the `uuid` library.  Either option is better than replicating its logic here.
</blockquote></details>

Thanks!
___
*[util/util.go, line 77 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_OwOrpBOohW45Ae2RO:-L_s5enO-e5R_6xKvxEM:bdrpzok) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/util/util.go#L77)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Please just take this in as a command-line parameter. No need to parse when it is explicitly specified.
</blockquote></details>

Please still do this.
___
*[util/util.go, line 87 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_OwjfM5rBsTLlnqABf:-L_s5jEY7g_nRSF9ivkd:bgizebl) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/util/util.go#L87)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

`os.MkdirAll` makes a lot of this code unnecessary.
</blockquote></details>

Followed up in another comment
___
*[util/util.go, line 110 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_OxZ_o006GY8-AY-DS:-L_s5nsk5f29lOEHVoQ3:b-ucfknh) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/util/util.go#L110)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Should be in its own package `ipcache`
</blockquote></details>

Thanks!
___
*[util/util.go, line 113 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_P1QvSAC39IYmsVSqx:-L_s5wkI2IezPyWcMR39:b-e6r3y2) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/util/util.go#L113)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Should be a flag in `main()` and then a `time.Duration` should be passed to `the New() function`
</blockquote></details>

Or make it a flag. This is followed up in another comment.
___
*[util/util.go, line 116 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_P3DqR2PGFyeGECRQ9:-L_s62ui6_k5Vje-m7Um:b-s6ay4t) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/util/util.go#L116)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

please use `map[string]time.Time` instead.
</blockquote></details>

Followed up in another comment. 


<!-- Sent from Reviewable.io -->

2019-03-13 21:20 UTC, pboothe requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

___
*[scamper/scamper.go, line 27 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_s1bDH1Dy3DbiJXuIB:-L_svGqT5hkCVX-E66In:b-6gvlh9) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/scamper/scamper.go#L27)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

This can be made much shorter using `os.MkdirAll`:

```
func createTimePath(prefix string) string {
  dir := prefix + "/" + time.Now().Format("2016/01/02") + "/" + GetHostnamePrefix()
  err := os.MkdirAll(dir, 0700)
  if err != nil { 
    return "" 
  }  
  return dir
}
```
</blockquote></details>

Or even:

```go
func createTimePath(prefix string) string {
  dir := prefix + "/" + time.Now().Format("2016/01/02") + "/" + GetHostnamePrefix()
  rtx.Must(os.MkdirAll(dir, 0700))
  return dir
}
```


<!-- Sent from Reviewable.io -->

2019-03-14 14:56 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

___
*[caller.go, line 59 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_OxvCI4ce26_hVOUsZ:-L_wh5AG23l-8beg99QE:bb6un1j) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/caller.go#L59)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

followed up in a separate comment.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2019-03-14 15:03 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[caller.go, line 156 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_OxEx4DynudiQyh8LH:-L_wibEz0CIJkFO5AX5n:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/caller.go#L156)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

This should still be a local var of `main`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-03-14 17:29 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[caller.go, line 165 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_OyYHR-rMRRw1NoY_x:-L_xF3mhBfMEpJCMl4vp:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/56714fd832b04609d7382e73abbf6d141cd8b718/caller.go#L165)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Still true.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-03-14 17:40 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[connection/connection.go, line 25 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_rxJne7zPizd84iwP6:-L_xFq0I1d0f05jfBHCq:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/connection/connection.go#L25)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Should be a method attached to the `Connection` struct.

```go
func (c *Connection) UUID() (string, error) {
  ...
}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-03-14 18:12 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[connection/connection.go, line 65 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_rxyW23PX26oRkDekb:-L_xOsTF0loqQJkgL8kq:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/connection/connection.go#L65)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Should be in `connectionwatcher`, along with `ParseCookie` and `ParseIPAndPort`.  Then they can be renamed to `parseSSLine`, `parseCookie`, and `parseIPAndPort`.  Then it's clear that these functions are only used inside `connectionwatcher` and users of the library don't need to know about them. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-03-14 18:32 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[connectionwatcher/connectionwatcher.go, line 20 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_s1Gzp5QEnipEWKnSH:-L_xPBm737r-tcBQJMeM:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/connectionwatcher/connectionwatcher.go#L20)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Should be `getConnections`
</blockquote></details>

Done.
___
*[connectionwatcher/connectionwatcher.go, line 41 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_s0i8bAus-vnFfhAhk:-L_xPYLcAazlX99QODI_:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/connectionwatcher/connectionwatcher.go#L41)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

This function is only used in the test. No need to export it, just put the test in `package connectionwatcher` and then this can be renamed to `getPoolSize`
</blockquote></details>

Done.
___
*[connectionwatcher/connectionwatcher.go, line 45 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_s0dCM5hn6abkd7Kyn:-L_xPZLVD5_KOq5l186Q:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/connectionwatcher/connectionwatcher.go#L45)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

This function is never used. Delete it.
</blockquote></details>

Done.
___
*[connectionwatcher/connectionwatcher.go, line 66 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_ryZZK-ce7V1q3Sd6h:-L_xSnwr5ydKLiMKJzfV:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/connectionwatcher/connectionwatcher.go#L66)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

The regular go idiom is to have a function `New` in a package instead of `Init` on an existing struct.

```go
func New() *ConnectionWatcher {
  c := &ConnectionWatcher{
    recentIPCache: ipcache.New(),
    connectionPool: make(map[connection.Connection]bool),
  }
  c.getConnections()  // prepare the cache
  return c
}
```

It also allows all client of this library to save a line and do:
`connWatcher := connectionwatcher.New()`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-03-14 19:12 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[ipcache/ipcache.go, line 22 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_s-nJkB9Q2wAACYeVv:-L_xa4T29tID7bvUSJvt:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/ipcache/ipcache.go#L22)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

add 
```go
if ctx.Err() != nil {
  return
}
```
before calling the inner for-loop.
</blockquote></details>

Done.
___
*[ipcache/ipcache.go, line 25 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_rztNOBoFdAiS5foRX:-L_xa98e9BudZO87S8kY:bs7wumx) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/ipcache/ipcache.go#L25)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Should be coverted to use time types. 

`if now.Add(IP_CACHE_LIFETIME).After(v) {`
</blockquote></details>

Done. 


<!-- Sent from Reviewable.io -->

2019-03-14 19:47 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[ipcache/ipcache.go, line 45 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_s3qfV7X8m38QPTnOA:-L_xjdHs2JHR4-Htli1q:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/ipcache/ipcache.go#L45)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Only used by a function that is never called.  Should be deleted when that function is deleted.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-03-14 19:49 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[ipcache/ipcache.go, line 39 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_s0L9h56_1-04HAvJE:-L_xkES9BYa9Oge6iFQ0:b-9unw5o) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/ipcache/ipcache.go#L39)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

If `Flush` gets called while the goroutine is in the middle of its `for k, v := range m.cache {` loop, what happens?  If what happens is okay, please put a comment explaining what happens and why it is okay.  If what happens is not okay, please fix.
</blockquote></details>

deleted


<!-- Sent from Reviewable.io -->

2019-03-14 20:00 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[scamper/scamper.go, line 18 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_s1PJy-iWzwbTxQK5f:-L_xkwYf8cRPRX8sSKzi:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/scamper/scamper.go#L18)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Thanks for making this a flag! Variable name should be `scamperBin`
</blockquote></details>

Done.
___
*[scamper/scamper.go, line 22 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_s3KRk8Q_P3PnHZ4v-:-L_xlGHKADuT1ddF67KK:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/scamper/scamper.go#L22)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Should be `createTimePath`
</blockquote></details>

Done.
___
*[scamper/scamper.go, line 27 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_s1bDH1Dy3DbiJXuIB:-L_xmIdMEEgnurJNcY6h:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/scamper/scamper.go#L27)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Or even:

```go
func createTimePath(prefix string) string {
  dir := prefix + "/" + time.Now().Format("2016/01/02") + "/" + GetHostnamePrefix()
  rtx.Must(os.MkdirAll(dir, 0700))
  return dir
}
```
</blockquote></details>

Done.
___
*[scamper/scamper.go, line 49 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_s3MXM3rKNvaJvFI1a:-L_xmVk19i8xegNtY4zl:bs7wumx) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/scamper/scamper.go#L49)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

should be `makeFilename`
</blockquote></details>

Done. 


<!-- Sent from Reviewable.io -->

2019-03-14 20:02 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[scamper/scamper.go, line 56 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_s3P5FBpnKixsJkA09:-L_xn7Hm76K4Os6ebWw0:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/scamper/scamper.go#L56)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

should be `getHostname`
</blockquote></details>

Done.
___
*[scamper/scamper.go, line 63 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_s3QreDyHM_XLBHAFW:-L_xn68AB89Kf7CBvcIx:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/scamper/scamper.go#L63)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

should be `getHostnamePrefix`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-03-14 20:02 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[scamper/scamper.go, line 74 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_s4_QG6qtHk5-QeClu:-L_xn9f3C7GOZeO7_z3R:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/scamper/scamper.go#L74)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Please add `//TODO: convert to using sc_attach`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-03-15 15:57 UTC, pboothe requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

___
*[ipcache/ipcache.go, line 22 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_s-nJkB9Q2wAACYeVv:-La0YDaR-fqTt7Ijk-Br:bvekynj) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/ipcache/ipcache.go#L22)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We miscommunicated.  The cancellation of the context should be able to cause to goroutine to stop and return, not prevent its initial creation.

So the check that I described has to happen inside the infinite loop in the goroutine.
___
*[scamper/scamper.go, line 27 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_s1bDH1Dy3DbiJXuIB:-La0YfqYC1EvBaIANFId:b-u9s94g) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/scamper/scamper.go#L27)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please use the `.Format` command to eliminate the need for creating and then immediately splitting and parsing the date string.  This is what my example code does, and it ends up saving another 5 lines and increasing readability.
___
*[scamper/scamper.go, line 30 at r7](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-La0Z-Jb7zUFAAm7W4Em:-La0Z-Jb7zUFAAm7W4En:barxizg) ([raw file](https://github.com/m-lab/traceroute-caller/blob/2a375af70ce71c3036e5ecc2a3323fa0ff021d14/scamper/scamper.go#L30)):*
> ```Go
> 	dir := prefix + "/" + date[0] + "/" + date[1] + "/" + date[2] + "/" + getHostnamePrefix()
> 	err := os.MkdirAll(dir, 0700)
> 	if err != nil {
> ```

What should the calling function do when this returns `""`? 

I suspect the answer is "it should exit the program", in which case you can use `rtx.Must` here and eliminate the need to worry about the error condition.
___
*[scamper/scamper.go, line 45 at r7](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-La112PF8PW5h4YiLu5x:-La112PF8PW5h4YiLu5y:by7ne5c) ([raw file](https://github.com/m-lab/traceroute-caller/blob/2a375af70ce71c3036e5ecc2a3323fa0ff021d14/scamper/scamper.go#L45)):*
> ```Go
> 
> // getHostname returns the hostname.
> func getHostname() string {
> ```

I just found out about the built-in function `os.Hostname()`  Let's use that instead of writing our own.
___
*[scamper/scamper.go, line 64 at r7](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-La11PM13slcWzgGyVXc:-La11PM13slcWzgGyVXd:b-wf7sll) ([raw file](https://github.com/m-lab/traceroute-caller/blob/2a375af70ce71c3036e5ecc2a3323fa0ff021d14/scamper/scamper.go#L64)):*
> ```Go
> // TODO: convert to use sc_attach
> func Run(conn connection.Connection, outputPath string) {
> 	command := exec.Command(*scamperBin, "-O", "json", "-I", "tracelb -P icmp-echo -q 3 -O ptr "+conn.Remote_ip)
> ```

Please break these arguments to `Command` up into separate strings
___
*[scamper/scamper.go, line 87 at r7](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-La127ojDEzRpXsycwb7:-La127ojDEzRpXsycwb8:b-whpjox) ([raw file](https://github.com/m-lab/traceroute-caller/blob/2a375af70ce71c3036e5ecc2a3323fa0ff021d14/scamper/scamper.go#L87)):*
> ```Go
> 
> 	if exitCode != 0 {
> 		log.Printf("call not exit correctly")
> ```

Do `log.Println(command.Path, command.Args, "exited unsuccessfully with code", exitCode)` instead


<!-- Sent from Reviewable.io -->

2019-03-15 15:59 UTC, pboothe reviewed
Added a few more comments. This is getting super close, and the code is getting a lot more modular. I can now much more easily feel confident about what code depends on what other code.

Thanks!

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-:-La13scX0zTuDmYuit0t:b-g1lkt9)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)



<!-- Sent from Reviewable.io -->

2019-03-18 15:05 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[ipcache/ipcache.go, line 17 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_s-aKNA0aPA1JeqGhi:-LaGKayq-9uKZaLR2Eoo:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/ipcache/ipcache.go#L17)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Pass in `ctx context.Context` as an argument to `New` to make it possible for callers to stop the newly-created goroutine.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-03-18 15:20 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[scamper/scamper.go, line 45 at r7](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-La112PF8PW5h4YiLu5x:-LaGNDm0EVcixq54sNl-:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/2a375af70ce71c3036e5ecc2a3323fa0ff021d14/scamper/scamper.go#L45)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

I just found out about the built-in function `os.Hostname()`  Let's use that instead of writing our own.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-03-18 15:24 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[scamper/scamper.go, line 87 at r7](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-La127ojDEzRpXsycwb7:-LaGOPvDAgzZC3HkuihK:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/2a375af70ce71c3036e5ecc2a3323fa0ff021d14/scamper/scamper.go#L87)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Do `log.Println(command.Path, command.Args, "exited unsuccessfully with code", exitCode)` instead
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-03-18 15:45 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[scamper/scamper.go, line 64 at r7](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-La11PM13slcWzgGyVXc:-LaGTTrPAE14c-6H7gDe:btcrcf9) ([raw file](https://github.com/m-lab/traceroute-caller/blob/2a375af70ce71c3036e5ecc2a3323fa0ff021d14/scamper/scamper.go#L64)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Please break these arguments to `Command` up into separate strings
</blockquote></details>

discussed offline. doc added.


<!-- Sent from Reviewable.io -->

2019-03-18 15:58 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe)

___
*[scamper/scamper.go, line 27 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_s1bDH1Dy3DbiJXuIB:-LaGWgvO51COm2p7rA8X:bb6un1j) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/scamper/scamper.go#L27)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Please use the `.Format` command to eliminate the need for creating and then immediately splitting and parsing the date string.  This is what my example code does, and it ends up saving another 5 lines and increasing readability.
</blockquote></details>

Done
___
*[scamper/scamper.go, line 30 at r7](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-La0Z-Jb7zUFAAm7W4Em:-LaGWhtLCUu3ofp069LC:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/2a375af70ce71c3036e5ecc2a3323fa0ff021d14/scamper/scamper.go#L30)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

What should the calling function do when this returns `""`? 

I suspect the answer is "it should exit the program", in which case you can use `rtx.Must` here and eliminate the need to worry about the error condition.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-03-18 16:21 UTC, pboothe requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

___
*[ipcache/ipcache.go, line 22 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_s-nJkB9Q2wAACYeVv:-LaGZSDP7E5WsrQph4x2:bs8k2hh) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/ipcache/ipcache.go#L22)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

We miscommunicated.  The cancellation of the context should be able to cause to goroutine to stop and return, not prevent its initial creation.

So the check that I described has to happen inside the infinite loop in the goroutine.
</blockquote></details>

Thanks! Now we have a new problem: `time.Tick` leaks a goroutine.

Please change 
```go
for now := range time.Tick(time.Second) {
```

to 
```go
ticker := time.NewTicker(time.Second)
defer ticker.Stop()
for now := range ticker.C {
```


<!-- Sent from Reviewable.io -->

2019-03-18 16:22 UTC, pboothe reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> one you make one last change

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-:-LaGaz21BaNMbLVTqhF1:b-7amizs)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)



<!-- Sent from Reviewable.io -->

2019-03-18 17:47 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe)

___
*[ipcache/ipcache.go, line 22 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/3#-L_s-nJkB9Q2wAACYeVv:-LaGudi-ApBS5n4xfv1f:bb6un1j) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9d63524e2ad65f64e315e81e9c4960c32e0cf06c/ipcache/ipcache.go#L22)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Thanks! Now we have a new problem: `time.Tick` leaks a goroutine.

Please change 
```go
for now := range time.Tick(time.Second) {
```

to 
```go
ticker := time.NewTicker(time.Second)
defer ticker.Stop()
for now := range ticker.C {
```

</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2019-03-18 17:54 UTC, merged