call ipservice from tracer
m-lab/traceroute-caller pull request #73
Opened 2020-05-05 00:13 UTC by yachang

2020-05-05 19:36 UTC, pboothe reviewed
I just added the ability to start a real instance of the IP annotation service, but backed with fake data in https://github.com/m-lab/uuid-annotator/pull/37 

Once that is merged, please use that service (see the `ExampleServer_forTesting` function in `server_test.go` for sample code) to verify that your client works correctly.

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-:-M6aJvol6mwVrPmbj7lb:b-8x4be3)* status: 0 of 1 approvals obtained (waiting on @pboothe)



<!-- Sent from Reviewable.io -->

2020-05-06 14:31 UTC, pboothe requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/73)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

___
*[caller_test.go, line 18 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M6eNaJ55Q1aMG0tFIot:-M6eNaJ63Xpxely5oDHy:b3etexz) ([raw file](https://github.com/m-lab/traceroute-caller/blob/a01d7cd0834544aff3b571b52eddbadf3cf5ae84/caller_test.go#L18)):*
> ```Go
> 
> func TestMetrics(t *testing.T) {
> 	promtest.LintMetrics(nil)
> ```

The problematic metric comes from using `annotation-service/api` inside of `traceroute-caller/parser/json.go`

`annotation-service` is no longer the authoritative source for those structs and that parsing.  Please use the structs inside of `uuid-annotator/annotator` instead.


<!-- Sent from Reviewable.io -->

2020-05-07 20:17 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/73)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe)

___
*[caller_test.go, line 18 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M6eNaJ55Q1aMG0tFIot:-M6kmLvL8lPnOJgr_ruW:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/a01d7cd0834544aff3b571b52eddbadf3cf5ae84/caller_test.go#L18)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

The problematic metric comes from using `annotation-service/api` inside of `traceroute-caller/parser/json.go`

`annotation-service` is no longer the authoritative source for those structs and that parsing.  Please use the structs inside of `uuid-annotator/annotator` instead.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-05-11 15:13 UTC, pboothe requested changes
Can we please refactor things to store structs internally instead of strings? Right now we repeatedly go back and forth between structured data and serialized strings, and it is confusing to read and wasteful of CPU time and RAM.

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-:-M73BAdF7qrPGN2rxE9O:b-zyrhu)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

___
*[parser/json.go, line 178 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M73G9JK66dWsoBzCLHI:-M73G9JK66dWsoBzCLHJ:ba4s50w) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9e1992711ef23ee3064bd7a7adb9bdaea08b3249/parser/json.go#L178)):*
> ```Go
> 					Source: schema.HopIP{
> 						IP:          oneNode.Addr,
> 						City:        hopAnn.Geo.City,
> ```

Please edit `schema.ScamperHop`.  Instead of City and CountryCode and ASN, please just have the elements `Geo *annotator.Geolocation` and `Network *annotator.Network`.

That way, traceroute caller never needs to understand the structure of the returned data, it is instead just added to the hop or not.   The pointer `*` is important, because it means that we can use `json:` comments to ensure that the `nil` value from ipservice will cause that entry not to be printed in the eventual json.
___
*[tracer/scamper.go, line 29 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M739uMl0f0HndQ1NCVu:-M739uMm9PJIXiqujVG8:b-q26ana) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9e1992711ef23ee3064bd7a7adb9bdaea08b3249/tracer/scamper.go#L29)):*
> ```Go
> )
> 
> var IPServiceSocketFilename = flag.String(
> ```

No need to do this. Use the flag already defined as `ipservice.SocketFilename` from the `ipservice` package
___
*[tracer/scamper.go, line 130 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M73A5WwEBeY9GnnTAoY:-M73A5WwEBeY9GnnTAoZ:b-jon6n2) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9e1992711ef23ee3064bd7a7adb9bdaea08b3249/tracer/scamper.go#L130)):*
> ```Go
> 		// Here we allow the original test sent back for cached test
> 		// when adding annotation did not succeed.
> 		return string(buff.Bytes()), err
> ```

I do not understand this comment. I suspect that it is confusing because of the string->struct->string->struct->string thing we are doing. Please let's stop doing that.
___
*[tracer/scamper.go, line 225 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M73ApLVEbPDYrEtTYPq:-M73ApLVEbPDYrEtTYPr:bf592gg) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9e1992711ef23ee3064bd7a7adb9bdaea08b3249/tracer/scamper.go#L225)):*
> ```Go
> 	var err error
> 	if len(iplist) > 0 {
> 		client := ipservice.NewClient(*IPServiceSocketFilename)
> ```

I had expected that you would only need to make a client once, and you could reuse that client for each traceroute.  Please pass in the client or pass in the socket filename. Adding a new dependency on a global variable makes things harder to test.


<!-- Sent from Reviewable.io -->

2020-05-11 15:52 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/73)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[parser/json.go, line 178 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M73G9JK66dWsoBzCLHI:-M73QRSt4leUjt4S6z1N:byyie8l) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9e1992711ef23ee3064bd7a7adb9bdaea08b3249/parser/json.go#L178)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Please edit `schema.ScamperHop`.  Instead of City and CountryCode and ASN, please just have the elements `Geo *annotator.Geolocation` and `Network *annotator.Network`.

That way, traceroute caller never needs to understand the structure of the returned data, it is instead just added to the hop or not.   The pointer `*` is important, because it means that we can use `json:` comments to ensure that the `nil` value from ipservice will cause that entry not to be printed in the eventual json.
</blockquote></details>

Will BigQuery traceroute table eventually also has all Geolocation and ASN info as well? Since the content of PTTestRaw will be copied in ETL parser w/o more processing as we designed. 


<!-- Sent from Reviewable.io -->

2020-05-12 02:57 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/73)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[tracer/scamper.go, line 130 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M73A5WwEBeY9GnnTAoY:-M75o5tp6Mzl9x8jzBTX:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9e1992711ef23ee3064bd7a7adb9bdaea08b3249/tracer/scamper.go#L130)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

I do not understand this comment. I suspect that it is confusing because of the string->struct->string->struct->string thing we are doing. Please let's stop doing that.
</blockquote></details>

Done.
___
*[tracer/scamper.go, line 225 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M73ApLVEbPDYrEtTYPq:-M75dYIf4JZEA5S_UfTw:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9e1992711ef23ee3064bd7a7adb9bdaea08b3249/tracer/scamper.go#L225)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

I had expected that you would only need to make a client once, and you could reuse that client for each traceroute.  Please pass in the client or pass in the socket filename. Adding a new dependency on a global variable makes things harder to test.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-05-12 03:37 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/73)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe)

___
*[tracer/scamper.go, line 29 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M739uMl0f0HndQ1NCVu:-M75xBDIAFGayc8DTliv:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9e1992711ef23ee3064bd7a7adb9bdaea08b3249/tracer/scamper.go#L29)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

No need to do this. Use the flag already defined as `ipservice.SocketFilename` from the `ipservice` package
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-05-12 16:17 UTC, pboothe requested changes
> Reviewed 1 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/73)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[ipcache/ipcache.go, line 23 at r8](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M78d3BG17rx13pNW0WJ:-M78d3BH7vndOLy8Bcaj:bxp2rhj) ([raw file](https://github.com/m-lab/traceroute-caller/blob/ebf5c97ac6e90578296195a576f2e64abdd719c6/ipcache/ipcache.go#L23)):*
> ```Go
> // Tracer is the generic interface for all things that can perform a traceroute.
> type Tracer interface {
> 	Trace(conn connection.Connection, t time.Time) ([]byte, error)
> ```

Trace should return something other than `string` or `[]byte`.

I suggest making it return an interface `TracerouteData` and giving `TracerouteData` the methods:
*  `Serialize() ([]byte, string)` where the `[]byte` is the data and the `string` is `json` or `jsonl` or some other format, 
* `AnnotateHops( ipservice.Client)` which annotates the hops, and 
* maybe `Metadata()` (the arguments and return value of `Metadata` are a little unclear to me right now, but I have an intuition that it might be needed, so I am putting it here).

Then we can make sure that parsed struct output from `tracer.Scamper` implements that interface, and we can make a very simple implementation for `tracer.Paris` which implements the `Serialize()` method by just returning the bytes and implements `AnnotateHops` by doing nothing at all.  Then all the annotation stuff moves into the Scamper struct methods (where it belongs, because we only know how to annotate scamper data) and the `cachedTest` can cache `TracerouteData` instead of `[]byte` or `string`. 

This "find the common interface of an internal type"  stuff is really complicated and tricky, but I think that this particular idea is likely the right one or close to the right one.  We are having problems because `[]byte` and `string` are not sophisticated enough types, so we keep having to parse them into more complicated types.  We should make the traceroute system (either Scamper or Paris) return those more complicated types directly, and have the more complicated types convert themselves into `[]byte` at the end when we save the data.
___
*[parser/json.go, line 178 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M73G9JK66dWsoBzCLHI:-M78WdbKEFA1tJEqBKzn:b6ssjjh) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9e1992711ef23ee3064bd7a7adb9bdaea08b3249/parser/json.go#L178)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Will BigQuery traceroute table eventually also has all Geolocation and ASN info as well? Since the content of PTTestRaw will be copied in ETL parser w/o more processing as we designed. 
</blockquote></details>

It will have all that information for the endpoints, but this is our only chance to put in that information for the hops.


<!-- Sent from Reviewable.io -->

2020-05-12 16:30 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/73)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[ipcache/ipcache.go, line 23 at r8](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M78d3BG17rx13pNW0WJ:-M78gzvZ817pHixcpb28:b-mkwl9u) ([raw file](https://github.com/m-lab/traceroute-caller/blob/ebf5c97ac6e90578296195a576f2e64abdd719c6/ipcache/ipcache.go#L23)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Trace should return something other than `string` or `[]byte`.

I suggest making it return an interface `TracerouteData` and giving `TracerouteData` the methods:
*  `Serialize() ([]byte, string)` where the `[]byte` is the data and the `string` is `json` or `jsonl` or some other format, 
* `AnnotateHops( ipservice.Client)` which annotates the hops, and 
* maybe `Metadata()` (the arguments and return value of `Metadata` are a little unclear to me right now, but I have an intuition that it might be needed, so I am putting it here).

Then we can make sure that parsed struct output from `tracer.Scamper` implements that interface, and we can make a very simple implementation for `tracer.Paris` which implements the `Serialize()` method by just returning the bytes and implements `AnnotateHops` by doing nothing at all.  Then all the annotation stuff moves into the Scamper struct methods (where it belongs, because we only know how to annotate scamper data) and the `cachedTest` can cache `TracerouteData` instead of `[]byte` or `string`. 

This "find the common interface of an internal type"  stuff is really complicated and tricky, but I think that this particular idea is likely the right one or close to the right one.  We are having problems because `[]byte` and `string` are not sophisticated enough types, so we keep having to parse them into more complicated types.  We should make the traceroute system (either Scamper or Paris) return those more complicated types directly, and have the more complicated types convert themselves into `[]byte` at the end when we save the data.
</blockquote></details>

We will annotate Paris Traceroute data later, using historical Maxmind datasets, and generate similar tar ball w/ same .json format. Eventually Gardener will only parse that single format of input (as we discussed in design https://docs.google.com/document/d/1HVHx63o5hQbKzZq6ZxsLl56Mwfr5hWgzc457Oq3GFzo/edit)

I will modify the tracer interface and get back to you.


<!-- Sent from Reviewable.io -->

2020-05-14 16:02 UTC, pboothe requested changes
I really like how this is cleaning up.  If we focus on making the TracerouteData interface meet all the needs, then I think we will end up with code that is much clearer, much more simple, and much more efficient.

Please use TracerouteData everywhere, and make sure you never need to cast or parse any of the strings it returns.

> Reviewed 2 of 9 files at r10.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-:-M7IuNg60RQRST4Yb7p8:b6lbmbi)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

___
*[ipcache/ipcache.go, line 23 at r8](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M78d3BG17rx13pNW0WJ:-M7IpYun1grDm-bLWXDE:b-b2i194) ([raw file](https://github.com/m-lab/traceroute-caller/blob/ebf5c97ac6e90578296195a576f2e64abdd719c6/ipcache/ipcache.go#L23)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

We will annotate Paris Traceroute data later, using historical Maxmind datasets, and generate similar tar ball w/ same .json format. Eventually Gardener will only parse that single format of input (as we discussed in design https://docs.google.com/document/d/1HVHx63o5hQbKzZq6ZxsLl56Mwfr5hWgzc457Oq3GFzo/edit)

I will modify the tracer interface and get back to you.
</blockquote></details>

The `ipcache` should now store `TracerouteData` instead of `string` or `[]byte`.
___
*[ipcache/ipcache.go, line 28 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7IsTVE5yiK9AGUYCCK:-M7IsTVE5yiK9AGUYCCL:byiebq8) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/ipcache/ipcache.go#L28)):*
> ```Go
> }
> 
> /*
> ```

Delete this commented-out code
___
*[parser/json.go, line 178 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M73G9JK66dWsoBzCLHI:-M7Ipjtt5ClzbMnStbqW:blm0eqn) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9e1992711ef23ee3064bd7a7adb9bdaea08b3249/parser/json.go#L178)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

It will have all that information for the endpoints, but this is our only chance to put in that information for the hops.
</blockquote></details>

Please change `schema.HopIP` to remove `City`, `CountryCode`, and `ASN` and instead add two fields `Geo *annotation.Geo` and `Network *annotation.Network`.  Annotation then becomes attaching a pointer.
___
*[tracer/paris.go, line 99 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7ItHaGE8OaMc6f-N0O:-M7ItHaGE8OaMc6f-N0P:b-ompqzd) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/tracer/paris.go#L99)):*
> ```Go
> 	}
> 	fn := p.filename(uuid, t, true)
> 	return ioutil.WriteFile(dir+fn, cachedTest.(*ParisData).GetData(), 0446)
> ```

You can't assume that the returned type is a `*ParisData`.  Only use the methods of `TracerouteData`.
___
*[tracer/scamper.go, line 31 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7IrTgZ7BCskAPseIPz:-M7IrTgZ7BCskAPseIQ-:bz1vgpq) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/tracer/scamper.go#L31)):*
> ```Go
> // ScamperData implement ipcache.TracerouteData
> type ScamperData struct {
> 	data []byte
> ```

This should be a `schema.PTTestRaw` struct, and the `[]byte` data from scamper should be parsed into the struct immediately upon collection.   Please keep the data in structured form internally, and only serialize it at the very end.  No code except the code that initially creates the `*ScamperData` should ever need to call the parser.

Also, please don't export `ScamperData`.  There's no need. Only export `TracerouteData`.
___
*[tracer/scamper.go, line 35 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7IrkTd5RRWh5KsH7_u:-M7IrkTd5RRWh5KsH7_v:b-wq34l) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/tracer/scamper.go#L35)):*
> ```Go
> 
> func (sd *ScamperData) Serialize() string {
> 	return string(sd.data)
> ```

This should `json.Marshal` the `schema.PTTestRaw` struct.
___
*[tracer/scamper.go, line 38 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7Ip6g9DmyFQsmyeSOh:-M7Ip6gA2G9m0C5Lr-tS:b1aqnpx) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/tracer/scamper.go#L38)):*
> ```Go
> }
> 
> func (sd *ScamperData) GetData() []byte {
> ```

What is GetData doing here? It should either not exist or it should be part of the TracerouteData interface.  I think it should not exist.
___
*[tracer/scamper.go, line 42 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7IrpUsAWOltp0HTb0L:-M7IrpUsAWOltp0HTb0M:b-37k4ps) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/tracer/scamper.go#L42)):*
> ```Go
> }
> 
> func (sd *ScamperData) AnnotateHops(client ipservice.Client) error {
> ```

AnnotateHops should not need to call the parser. The data should already be parsed.
___
*[tracer/scamper.go, line 56 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7IsI8eDtUbJiJiWcDB:-M7IsI8eDtUbJiJiWcDC:b-jhlxnh) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/tracer/scamper.go#L56)):*
> ```Go
> 
> 	// add annotation to the final output
> 	sd.data, err = parser.InsertAnnotation(ann, sd.data)
> ```

This serializes things too soon.  Please don't serialize the data until you are asked to do so in the `Serialize` method.
___
*[tracer/scamper.go, line 87 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7IqHnWEnCyHGh18YKf:-M7IqHnWEnCyHGh18YKg:b-f9hy7p) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/tracer/scamper.go#L87)):*
> ```Go
> 	// remove the first line of cachedTest
> 	var cachedTestJson schema.PTTestRaw
> 	err = json.Unmarshal(cachedTest.(*ScamperData).GetData(), &cachedTestJson)
> ```

You can't assume that the `cachedTest` is a `*ScamperData`. It could be a `*ParisData`.  Please ONLY use the methods of the `TracerouteData` interface.  If converting a trace into a cached trace is a fundamental thing that all `TracerouteData` should be able to do, then please add to the `TracerouteData` interface a method `CachedResult(newuuid string) TracerouteData` that creates a new struct with the fields filled in appropriately.


<!-- Sent from Reviewable.io -->

2020-05-14 17:26 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/73)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[ipcache/ipcache.go, line 28 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7IsTVE5yiK9AGUYCCK:-M7JDINV1DfPbDr4OkMb:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/ipcache/ipcache.go#L28)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Delete this commented-out code
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-05-14 17:56 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/73)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[parser/json.go, line 178 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M73G9JK66dWsoBzCLHI:-M7JK3OrE2CA5sURjdoc:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/9e1992711ef23ee3064bd7a7adb9bdaea08b3249/parser/json.go#L178)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Please change `schema.HopIP` to remove `City`, `CountryCode`, and `ASN` and instead add two fields `Geo *annotation.Geo` and `Network *annotation.Network`.  Annotation then becomes attaching a pointer.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-05-14 18:03 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/73)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[tracer/paris.go, line 99 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7ItHaGE8OaMc6f-N0O:-M7JK9jAChQDXdR3Uf1f:b-qav6eg) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/tracer/paris.go#L99)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

You can't assume that the returned type is a `*ParisData`.  Only use the methods of `TracerouteData`.
</blockquote></details>

This func is for Paris, so I can assume it is ParisData.

I add GetData() to TracerouteData interface which might be a better solution.


<!-- Sent from Reviewable.io -->

2020-05-14 21:14 UTC, pboothe requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/73)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[tracer/paris.go, line 99 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7ItHaGE8OaMc6f-N0O:-M7K0zjF4W-VMp96wuXz:b-99kgj6) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/tracer/paris.go#L99)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

This func is for Paris, so I can assume it is ParisData.

I add GetData() to TracerouteData interface which might be a better solution.
</blockquote></details>

You can't assume that, because of the failover logic that allows traceroute-caller to transition from using one kind of test to using another.  I think we should eliminate the need for `TracedFromCahchedTrace` to have access to the underlying bytes by adding `CachedResult(newuuid string) TracerouteData` to the TracerouteData interface.


<!-- Sent from Reviewable.io -->

2020-05-15 03:49 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/73)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[ipcache/ipcache.go, line 23 at r8](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M78d3BG17rx13pNW0WJ:-M7LPW-8DZQqONTWvh-E:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/ebf5c97ac6e90578296195a576f2e64abdd719c6/ipcache/ipcache.go#L23)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

The `ipcache` should now store `TracerouteData` instead of `string` or `[]byte`.
</blockquote></details>

Done.
___
*[tracer/paris.go, line 99 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7ItHaGE8OaMc6f-N0O:-M7LQrkj36lyV2gqMGzq:b-n75a2u) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/tracer/paris.go#L99)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

You can't assume that, because of the failover logic that allows traceroute-caller to transition from using one kind of test to using another.  I think we should eliminate the need for `TracedFromCahchedTrace` to have access to the underlying bytes by adding `CachedResult(newuuid string) TracerouteData` to the TracerouteData interface.
</blockquote></details>

For paris, we need not alter the test content, and I use GetData() directly, which is in TracerouteData interface now.

For scamper, we need to modify the underlying content, I add a GetStructureData() func for ScamperData only


<!-- Sent from Reviewable.io -->

2020-05-15 03:53 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/73)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe)

___
*[tracer/scamper.go, line 31 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7IrTgZ7BCskAPseIPz:-M7LSL7XABlEYX88d7BF:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/tracer/scamper.go#L31)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

This should be a `schema.PTTestRaw` struct, and the `[]byte` data from scamper should be parsed into the struct immediately upon collection.   Please keep the data in structured form internally, and only serialize it at the very end.  No code except the code that initially creates the `*ScamperData` should ever need to call the parser.

Also, please don't export `ScamperData`.  There's no need. Only export `TracerouteData`.
</blockquote></details>

Done.
___
*[tracer/scamper.go, line 35 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7IrkTd5RRWh5KsH7_u:-M7LSNHXBEZu07mZPARc:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/tracer/scamper.go#L35)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

This should `json.Marshal` the `schema.PTTestRaw` struct.
</blockquote></details>

Done.
___
*[tracer/scamper.go, line 38 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7Ip6g9DmyFQsmyeSOh:-M7LSQp38oHMyKjT5bHY:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/tracer/scamper.go#L38)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

What is GetData doing here? It should either not exist or it should be part of the TracerouteData interface.  I think it should not exist.
</blockquote></details>

Done.
___
*[tracer/scamper.go, line 42 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7IrpUsAWOltp0HTb0L:-M7LST6QD5dPblb54pWT:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/tracer/scamper.go#L42)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

AnnotateHops should not need to call the parser. The data should already be parsed.
</blockquote></details>

Done.
___
*[tracer/scamper.go, line 56 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7IsI8eDtUbJiJiWcDB:-M7LSXYxEIPYR-Uh2FLS:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/tracer/scamper.go#L56)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

This serializes things too soon.  Please don't serialize the data until you are asked to do so in the `Serialize` method.
</blockquote></details>

Done.
___
*[tracer/scamper.go, line 87 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7IqHnWEnCyHGh18YKf:-M7LSim5-qkv1x8jN6IP:b-bang1d) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/tracer/scamper.go#L87)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

You can't assume that the `cachedTest` is a `*ScamperData`. It could be a `*ParisData`.  Please ONLY use the methods of the `TracerouteData` interface.  If converting a trace into a cached trace is a fundamental thing that all `TracerouteData` should be able to do, then please add to the `TracerouteData` interface a method `CachedResult(newuuid string) TracerouteData` that creates a new struct with the fields filled in appropriately.
</blockquote></details>

Answered above.


<!-- Sent from Reviewable.io -->

2020-05-15 14:47 UTC, pboothe requested changes
> Reviewed 3 of 11 files at r11.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/73)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

___
*[schema/schema.go, line 12 at r11](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7NkW-zCqOGn3xS8ueB:-M7NkW0-8SZvhWe8RCU7:b-ucfknh) ([raw file](https://github.com/m-lab/traceroute-caller/blob/33b8c6d1d6eaba44749c0054a48ecb2179da6122/schema/schema.go#L12)):*
> ```Go
> 	IP       string                 `json:"ip,string"`
> 	Hostname string                 `json:"hostname,string"`
> 	Geo      *annotator.Geolocation `json:"geo"`
> ```

Thanks!
___
*[tracer/paris.go, line 99 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7ItHaGE8OaMc6f-N0O:-M7NhYRc062g2GI6HUUL:b9uij6s) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/tracer/paris.go#L99)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

For paris, we need not alter the test content, and I use GetData() directly, which is in TracerouteData interface now.

For scamper, we need to modify the underlying content, I add a GetStructureData() func for ScamperData only
</blockquote></details>

You can't and shouldn't assume the the data you get out of the `ipcache` will be the type you are expecting.  Please don't do that. (which is what you are doing here, by adding a `GetData` method that makes assumptions about the data contained in the bytes).  Please use `Serialize()` here (and if you want Serialize to return `[]byte` instead of `string` that's fine - whichever is easier for you)

Instead, a method `CachedTraceroute(newuuid string)  TracerouteData` should be added to the `TracerouteData` interface.  This code would then become:

```go
data := cachedTest.CachedTraceroute(conn.UUID())
return ioutil.WriteFile(dir+fn, data.Serialize(), 0446)
```
___
*[tracer/scamper.go, line 31 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7IrTgZ7BCskAPseIPz:-M7Nj7tW0FCX087vdgHr:b6kog53) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/tracer/scamper.go#L31)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please don't export `ScamperData`.  Please rename`type ScamperData struct`  to `type scamperData struct`.  Please also rename `ParisData` to `parisData`.
___
*[tracer/scamper.go, line 38 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7Ip6g9DmyFQsmyeSOh:-M7NkbAa1bMwR3m6miXS:b-ex7iwn) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/tracer/scamper.go#L38)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`GetData` should be removed from the `TracerouteData` interface and deleted here.
___
*[tracer/scamper.go, line 87 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7IqHnWEnCyHGh18YKf:-M7NjWBn-QfA-6P7aX64:bsoqvk0) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/tracer/scamper.go#L87)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Answered above.
</blockquote></details>

See above comment.

This code should be:
```go
        cachedTestJson := cachedTest.CachedTraceroute(conn.UUID())
	newTest, err := json.Marshal(cachedTestJson)
	if err == nil {
		return ioutil.WriteFile(filename, []byte(newTest), 0666)
	}
	return err
```
___
*[tracer/scamper.go, line 42 at r11](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7NnDSOAAQV4pwNcWhW:-M7NnDSOAAQV4pwNcWhX:b-s1v2cq) ([raw file](https://github.com/m-lab/traceroute-caller/blob/33b8c6d1d6eaba44749c0054a48ecb2179da6122/tracer/scamper.go#L42)):*
> ```Go
> }
> 
> func (sd *ScamperData) GetStructureData() schema.PTTestRaw {
> ```

Please don't create an extra method that you have to cast things to use.  Delete this method.
___
*[tracer/scamper.go, line 55 at r11](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7NlhGk1xFFVZNGIqWM:-M7NlhGk1xFFVZNGIqWN:b-2cze5v) ([raw file](https://github.com/m-lab/traceroute-caller/blob/33b8c6d1d6eaba44749c0054a48ecb2179da6122/tracer/scamper.go#L55)):*
> ```Go
> 
> func (sd *ScamperData) AnnotateHops(client ipservice.Client) error {
> 	iplist := parser.ExtractIP(sd.data)
> ```

`ExtractIP` should be a method attached to `PTTestRaw` structs and not part of the `parser` package.  It no longer parses anything.  Or it could be kept as a free function and moved to this package.
___
*[tracer/scamper.go, line 68 at r11](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7NmKr57f0Wu2Bi2i9J:-M7NmKr57f0Wu2Bi2i9K:b-shlund) ([raw file](https://github.com/m-lab/traceroute-caller/blob/33b8c6d1d6eaba44749c0054a48ecb2179da6122/tracer/scamper.go#L68)):*
> ```Go
> 
> 	// add annotation to the final output
> 	sd.data = parser.InsertAnnotation(ann, sd.data)
> ```

`InsertAnnotation` should have the exact same thing that happens to `ExtractIP` happen to it.  I suggested two options previously - either is fine with me here as well, but please choose the same option for both functions.  It also no longer parses anything, so no longer belongs in the `parser` package.


<!-- Sent from Reviewable.io -->

2020-05-15 16:49 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/73)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[tracer/scamper.go, line 87 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7IqHnWEnCyHGh18YKf:-M7OCNQSDfL3lC0AHRmR:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/tracer/scamper.go#L87)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

See above comment.

This code should be:
```go
        cachedTestJson := cachedTest.CachedTraceroute(conn.UUID())
	newTest, err := json.Marshal(cachedTestJson)
	if err == nil {
		return ioutil.WriteFile(filename, []byte(newTest), 0666)
	}
	return err
```
</blockquote></details>

Done.
___
*[tracer/scamper.go, line 55 at r11](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7NlhGk1xFFVZNGIqWM:-M7ODpvD4jAvgDUFcwD-:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/33b8c6d1d6eaba44749c0054a48ecb2179da6122/tracer/scamper.go#L55)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

`ExtractIP` should be a method attached to `PTTestRaw` structs and not part of the `parser` package.  It no longer parses anything.  Or it could be kept as a free function and moved to this package.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-05-15 16:50 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/73)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[tracer/scamper.go, line 38 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7Ip6g9DmyFQsmyeSOh:-M7OEMdV7Bsz6vLEG1-n:b-5v918u) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/tracer/scamper.go#L38)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

`GetData` should be removed from the `TracerouteData` interface and deleted here.
</blockquote></details>

I need it for TraceFromCachedTrace() final step (write []byte to file)


<!-- Sent from Reviewable.io -->

2020-05-15 17:06 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/73)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[tracer/scamper.go, line 31 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7IrTgZ7BCskAPseIPz:-M7OIDKiDjl5gtmhLivH:bb6un1j) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/tracer/scamper.go#L31)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Please don't export `ScamperData`.  Please rename`type ScamperData struct`  to `type scamperData struct`.  Please also rename `ParisData` to `parisData`.
</blockquote></details>

Done
___
*[tracer/scamper.go, line 42 at r11](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7NnDSOAAQV4pwNcWhW:-M7OH19l7WF6jQtQdhxW:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/33b8c6d1d6eaba44749c0054a48ecb2179da6122/tracer/scamper.go#L42)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Please don't create an extra method that you have to cast things to use.  Delete this method.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-05-15 17:08 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/73)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[tracer/paris.go, line 99 at r10](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7ItHaGE8OaMc6f-N0O:-M7OIe_g-dBx1b2AnTrw:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/593c5b522e0f291adf73ae3726d15465aff342b9/tracer/paris.go#L99)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

You can't and shouldn't assume the the data you get out of the `ipcache` will be the type you are expecting.  Please don't do that. (which is what you are doing here, by adding a `GetData` method that makes assumptions about the data contained in the bytes).  Please use `Serialize()` here (and if you want Serialize to return `[]byte` instead of `string` that's fine - whichever is easier for you)

Instead, a method `CachedTraceroute(newuuid string)  TracerouteData` should be added to the `TracerouteData` interface.  This code would then become:

```go
data := cachedTest.CachedTraceroute(conn.UUID())
return ioutil.WriteFile(dir+fn, data.Serialize(), 0446)
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-05-15 17:19 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/73)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe)

___
*[tracer/scamper.go, line 68 at r11](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7NmKr57f0Wu2Bi2i9J:-M7OKyQ92aAEK7ypwbsl:bfal0ek) ([raw file](https://github.com/m-lab/traceroute-caller/blob/33b8c6d1d6eaba44749c0054a48ecb2179da6122/tracer/scamper.go#L68)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

`InsertAnnotation` should have the exact same thing that happens to `ExtractIP` happen to it.  I suggested two options previously - either is fine with me here as well, but please choose the same option for both functions.  It also no longer parses anything, so no longer belongs in the `parser` package.
</blockquote></details>

Ideally, these 2 funcs should be with schema package. But given only Scamper use PTTestRaw in this way, I moved them to /tracer package for now.


<!-- Sent from Reviewable.io -->

2020-05-15 18:08 UTC, pboothe requested changes
> Reviewed 1 of 9 files at r12.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/73)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

___
*[ipcache/ipcache.go, line 24 at r12](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7ON50kE574CM22lGs7:-M7ON50kE574CM22lGs8:bay5cwq) ([raw file](https://github.com/m-lab/traceroute-caller/blob/8fde9be9cbe2d0364b2f4fa613d87ec07db0e555/ipcache/ipcache.go#L24)):*
> ```Go
> // TracerouteData is the generic interface for data generated by Scamper or Paris Traceroute.
> type TracerouteData interface {
> 	Serialize() string
> ```

Please delete `Serialize`.  Everything I was imagining you would do with `Serialize`, you are actually doing with `GetData`
___
*[ipcache/ipcache.go, line 27 at r12](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7OVF100cgcAypJF5hI:-M7OVF11Bnx7wdNvWywr:bn0lhjg) ([raw file](https://github.com/m-lab/traceroute-caller/blob/8fde9be9cbe2d0364b2f4fa613d87ec07db0e555/ipcache/ipcache.go#L27)):*
> ```Go
> 	GetData() []byte
> 	AnnotateHops(ipservice.Client) error
> 	CacheTraceroute(newUUID string) TracerouteData
> ```

Please call this function `CachedTraceroute` or `CreateCachedTraceroute`
___
*[ipcache/ipcache_test.go, line 31 at r12](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7OVrlv5RgC3M7Ju064:-M7OVrlv5RgC3M7Ju065:bpvn6wg) ([raw file](https://github.com/m-lab/traceroute-caller/blob/8fde9be9cbe2d0364b2f4fa613d87ec07db0e555/ipcache/ipcache_test.go#L31)):*
> ```Go
> }
> 
> func (td testData) Serialize() string {
> ```

Delete Serialize
___
*[tracer/paris.go, line 20 at r12](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7OVvgyDYcJary3VQQG:-M7OVvgz3InbSFAlRuZQ:bpvn6wg) ([raw file](https://github.com/m-lab/traceroute-caller/blob/8fde9be9cbe2d0364b2f4fa613d87ec07db0e555/tracer/paris.go#L20)):*
> ```Go
> }
> 
> func (pd *parisData) Serialize() string {
> ```

Delete Serialize
___
*[tracer/scamper.go, line 68 at r11](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7NmKr57f0Wu2Bi2i9J:-M7OMqYmCHNMijBuMljG:b-uv3mdl) ([raw file](https://github.com/m-lab/traceroute-caller/blob/33b8c6d1d6eaba44749c0054a48ecb2179da6122/tracer/scamper.go#L68)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Ideally, these 2 funcs should be with schema package. But given only Scamper use PTTestRaw in this way, I moved them to /tracer package for now.
</blockquote></details>

SGTM. Please also lower-case the methods to make them no longer exported, as their only use is now inside the same package in which they are defined.  
___
*[tracer/scamper.go, line 56 at r12](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7ONV7f1ZApv-IMRu3S:-M7ONV7f1ZApv-IMRu3T:b94lir4) ([raw file](https://github.com/m-lab/traceroute-caller/blob/8fde9be9cbe2d0364b2f4fa613d87ec07db0e555/tracer/scamper.go#L56)):*
> ```Go
> }
> 
> func (sd *scamperData) Serialize() string {
> ```

Serialize and GetData now do the same thing. Please delete `Serialize` and change all users of Serialize to use GetData.
___
*[tracer/scamper.go, line 124 at r12](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7ONeaX1N5aJhfvG_Mp:-M7ONeaX1N5aJhfvG_Mq:bmcdb8c) ([raw file](https://github.com/m-lab/traceroute-caller/blob/8fde9be9cbe2d0364b2f4fa613d87ec07db0e555/tracer/scamper.go#L124)):*
> ```Go
> 	log.Println("Starting a cached trace to be put in", filename)
> 
> 	newUUID, _ := conn.UUID()
> ```

Please don't disregard the error. If conn.UUID() returns an error then this whole function should return that error.


<!-- Sent from Reviewable.io -->

2020-05-15 19:09 UTC, yachang reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/73)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe)

___
*[ipcache/ipcache.go, line 24 at r12](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7ON50kE574CM22lGs7:-M7OdjXM7EhXiZsnba2O:bb6un1j) ([raw file](https://github.com/m-lab/traceroute-caller/blob/8fde9be9cbe2d0364b2f4fa613d87ec07db0e555/ipcache/ipcache.go#L24)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Please delete `Serialize`.  Everything I was imagining you would do with `Serialize`, you are actually doing with `GetData`
</blockquote></details>

Done
___
*[ipcache/ipcache.go, line 27 at r12](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7OVF100cgcAypJF5hI:-M7OjPMo3FhKvEGdmxKu:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/8fde9be9cbe2d0364b2f4fa613d87ec07db0e555/ipcache/ipcache.go#L27)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Please call this function `CachedTraceroute` or `CreateCachedTraceroute`
</blockquote></details>

Done.
___
*[ipcache/ipcache_test.go, line 31 at r12](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7OVrlv5RgC3M7Ju064:-M7OjQkLEnwB5Aci7jC4:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/8fde9be9cbe2d0364b2f4fa613d87ec07db0e555/ipcache/ipcache_test.go#L31)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Delete Serialize
</blockquote></details>

Done.
___
*[tracer/paris.go, line 20 at r12](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7OVvgyDYcJary3VQQG:-M7OjRmx5FtWHVVySWAW:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/8fde9be9cbe2d0364b2f4fa613d87ec07db0e555/tracer/paris.go#L20)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Delete Serialize
</blockquote></details>

Done.
___
*[tracer/scamper.go, line 68 at r11](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7NmKr57f0Wu2Bi2i9J:-M7OjUIXDDwBG6wqvmwI:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/33b8c6d1d6eaba44749c0054a48ecb2179da6122/tracer/scamper.go#L68)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

SGTM. Please also lower-case the methods to make them no longer exported, as their only use is now inside the same package in which they are defined.  
</blockquote></details>

Done.
___
*[tracer/scamper.go, line 56 at r12](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7ONV7f1ZApv-IMRu3S:-M7OjSueEpgdX78NiDu5:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/8fde9be9cbe2d0364b2f4fa613d87ec07db0e555/tracer/scamper.go#L56)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Serialize and GetData now do the same thing. Please delete `Serialize` and change all users of Serialize to use GetData.
</blockquote></details>

Done.
___
*[tracer/scamper.go, line 124 at r12](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-M7ONeaX1N5aJhfvG_Mp:-M7Oe9AtEc_xwTI1E17Q:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/8fde9be9cbe2d0364b2f4fa613d87ec07db0e555/tracer/scamper.go#L124)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Please don't disregard the error. If conn.UUID() returns an error then this whole function should return that error.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-05-15 19:15 UTC, pboothe approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

Thank you again for being willing to go back and forth on this. I think this new design is definitely superior to the old one, and will make future maintenance much easier.

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/73#-:-M7Okd6JCDix85-8s4xL:b-nn21es)* status: :shipit: complete! 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2020-05-15 20:14 UTC, pboothe commented
(also, please either get the test coverage back to 100% or file an issue to get the coverage back to 100%)

2020-05-15 22:14 UTC, merged